image: archlinux
packages:
  - nodejs
  - yarn
environment:
  build_env: production
  project: rss-irc-bot
sources:
  - https://github.com/MaxLeiter/rss-irc-bot
tasks:
  - prepare: |
      cd ${project}
      yarn
  - test: |
      cd ${project}
      yarn test